### ISSUE TITLE
Fatal error for getModel() with dynamic parameter

### ISSUE THREAD

**Issue by sreichel** [inviqa/phpstan-magento1#2]
Hi,

got this error for `Mage_Cron_Model_Observer::_processJob()`

    Uncaught PHPStan\ShouldNotHappenException: Internal error. in /var/www/html/magento-lts/vendor/inviqa/phpstan-magento1/src/Type/Mage/HelperMethodsReturnTypeExtension.php:40

First parameter for `getModel()` cause this ...

                if (!($model = Mage::getModel($run[1])) || !method_exists($model, $run[2])) {
                    Mage::throwException(Mage::helper('cron')->__('Invalid callback: %s::%s does not exist', $run[1], $run[2]));
                }

Any ideas how to fix?

**Comment by tmotyl** [comment]
Seems the issue is with dynamic class names. The phpstan-magento1 expects to get a string, while it's getting a variable containing string. 
```
if (! isset($methodCall->args[0]) || ! $methodCall->args[0]->value instanceof String_) {
            throw new ShouldNotHappenException("type:" . \get_class($methodCall->args[0]->value));
        }
```
